vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|21 Aug 2012 13:25:11 -0000
vti_extenderversion:SR|12.0.0.0
vti_author:SR|NBS\\ambl0001
vti_modifiedby:SR|NBS\\ambl0001
vti_timecreated:TR|10 Nov 2010 16:02:08 -0000
vti_nexttolasttimemodified:TW|20 Aug 2012 14:46:12 -0000
vti_backlinkinfo:VX|
vti_cacheddtm:TX|21 Aug 2012 13:25:11 -0000
vti_filesize:IR|6886
vti_cachedbodystyle:SR|<body id="NHSBT">
vti_cachedlinkinfo:VX|H|<%=dotdotpath%> H|<%=dotdotpath%>strategic_objectives/ H|<%=dotdotpath%>strategic_objectives/strategic_plan_2011_2014/ H|<%=dotdotpath%>strategic_objectives/blood_components/ H|<%=dotdotpath%>strategic_objectivesorgan_donation_and_transplantation/ H|<%=dotdotpath%>strategic_objectives/tissues/ H|<%=dotdotpath%>strategic_objectives/diagnostic_services/ H|<%=dotdotpath%>strategic_objectives/stem_cells/ H|<%=dotdotpath%>strategic_objectivesspecialist_services/ H|<%=dotdotpath%>strategic_objectivesnhsbt_corporate/ H|<%=dotdotpath%>blood_components/ H|<%=dotdotpath%>blood_components/strategic_targets/ H|<%=dotdotpath%>organ_donation_and_transplantation/ H|<%=dotdotpath%>organ_donation_and_transplantation/strategic_targets/ H|<%=dotdotpath%>tissues/ H|<%=dotdotpath%>tissues/strategic_targets/ H|<%=dotdotpath%>diagnostic_services/ H|<%=dotdotpath%>diagnostic_services/strategic_targets/ H|<%=dotdotpath%>stem_cell_services/ H|<%=dotdotpath%>stem_cell_services/strategic_targets/ H|<%=dotdotpath%>specialist_services/ H|<%=dotdotpath%>specialist_therapeutic_services/strategic_targets/ H|<%=dotdotpath%>nhsbt_corporate/ H|<%=dotdotpath%>nhsbt_corporate/strategic_targets/ H|<%=dotdotpath%>financial_overview/ H|<%=dotdotpath%>financial_overview/revenue/ H|<%=dotdotpath%>financial_overview/revenue_investment_plan/ H|<%=dotdotpath%>financial_overview/capital_investment_plan/ H|<%=dotdotpath%>financial_overview/performance_and_assurance/ H|<%=dotdotpath%>about_us/ H|<%=dotdotpath%>about_us/our_achievements.asp H|<%=dotdotpath%>about_us/our_priorities.asp
vti_cachedsvcrellinks:VX|UHUS|<%=dotdotpath%> UHUS|<%=dotdotpath%>strategic_objectives/ UHUS|<%=dotdotpath%>strategic_objectives/strategic_plan_2011_2014/ UHUS|<%=dotdotpath%>strategic_objectives/blood_components/ UHUS|<%=dotdotpath%>strategic_objectivesorgan_donation_and_transplantation/ UHUS|<%=dotdotpath%>strategic_objectives/tissues/ UHUS|<%=dotdotpath%>strategic_objectives/diagnostic_services/ UHUS|<%=dotdotpath%>strategic_objectives/stem_cells/ UHUS|<%=dotdotpath%>strategic_objectivesspecialist_services/ UHUS|<%=dotdotpath%>strategic_objectivesnhsbt_corporate/ UHUS|<%=dotdotpath%>blood_components/ UHUS|<%=dotdotpath%>blood_components/strategic_targets/ UHUS|<%=dotdotpath%>organ_donation_and_transplantation/ UHUS|<%=dotdotpath%>organ_donation_and_transplantation/strategic_targets/ UHUS|<%=dotdotpath%>tissues/ UHUS|<%=dotdotpath%>tissues/strategic_targets/ UHUS|<%=dotdotpath%>diagnostic_services/ UHUS|<%=dotdotpath%>diagnostic_services/strategic_targets/ UHUS|<%=dotdotpath%>stem_cell_services/ UHUS|<%=dotdotpath%>stem_cell_services/strategic_targets/ UHUS|<%=dotdotpath%>specialist_services/ UHUS|<%=dotdotpath%>specialist_therapeutic_services/strategic_targets/ UHUS|<%=dotdotpath%>nhsbt_corporate/ UHUS|<%=dotdotpath%>nhsbt_corporate/strategic_targets/ UHUS|<%=dotdotpath%>financial_overview/ UHUS|<%=dotdotpath%>financial_overview/revenue/ UHUS|<%=dotdotpath%>financial_overview/revenue_investment_plan/ UHUS|<%=dotdotpath%>financial_overview/capital_investment_plan/ UHUS|<%=dotdotpath%>financial_overview/performance_and_assurance/ UHUS|<%=dotdotpath%>about_us/ UHUS|<%=dotdotpath%>about_us/our_achievements.asp UHUS|<%=dotdotpath%>about_us/our_priorities.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
